DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id NUMBER(10, 0) NOT NULL PRIMARY KEY,
    name varchar(255) not null
);

DROP SEQUENCE IF EXISTS MY_SEQ;
CREATE SEQUENCE MY_SEQ MINVALUE 1 MAXVALUE 99999 INCREMENT BY 2 START WITH 3 NOCACHE NOCYCLE;